// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateEmailVerificationParams struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, createEmailVerification, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredEmailVerifications = `-- name: DeleteExpiredEmailVerifications :exec
DELETE FROM email_verifications
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredEmailVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailVerifications)
	return err
}

const getEmailVerification = `-- name: GetEmailVerification :one
SELECT token, user_id, expires_at, used_at, created_at FROM email_verifications
WHERE token = $1
`

func (q *Queries) GetEmailVerification(ctx context.Context, token string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerification, token)
	var i EmailVerification
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications
SET used_at = now()
WHERE token = $1
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markEmailVerificationUsed, token)
	return err
}
