// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerification struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PasswordReset struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	IpAddress string
	UserAgent string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	Role            string
	IsEmailVerified bool
	TotpSecret      pgtype.Text
	TotpEnabled     bool
	FailedLogins    int32
	LockedUntil     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Name            string
}
