// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	KeyHash    string
	Prefix     string
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type EmailVerification struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type OauthAuthCode struct {
	CodeHash      string
	ClientID      string
	UserID        pgtype.UUID
	RedirectUri   string
	CodeChallenge string
	Scope         string
	Resource      string
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type OauthClient struct {
	ClientID     string
	ClientName   string
	RedirectUris []string
	CreatedAt    pgtype.Timestamptz
}

type OauthRefreshToken struct {
	TokenHash string
	ClientID  string
	UserID    pgtype.UUID
	Scope     string
	Resource  string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PasswordReset struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	IpAddress string
	UserAgent string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	UserAgent  pgtype.Text
	Device     pgtype.Text
	Browser    pgtype.Text
	Os         pgtype.Text
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	Role            string
	IsEmailVerified bool
	TotpSecret      pgtype.Text
	TotpEnabled     bool
	FailedLogins    int32
	LockedUntil     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Name            string
	Bio             string
}
