// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthCode = `-- name: CreateAuthCode :exec
INSERT INTO oauth_auth_codes (
    code_hash, client_id, user_id, redirect_uri, code_challenge, scope, resource, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuthCodeParams struct {
	CodeHash      string
	ClientID      string
	UserID        pgtype.UUID
	RedirectUri   string
	CodeChallenge string
	Scope         string
	Resource      string
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createAuthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.Scope,
		arg.Resource,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (client_id, client_name, redirect_uris)
VALUES ($1, $2, $3)
RETURNING client_id, client_name, redirect_uris, created_at
`

type CreateOAuthClientParams struct {
	ClientID     string
	ClientName   string
	RedirectUris []string
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient, arg.ClientID, arg.ClientName, arg.RedirectUris)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthRefreshToken = `-- name: CreateOAuthRefreshToken :exec
INSERT INTO oauth_refresh_tokens (token_hash, client_id, user_id, scope, resource, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOAuthRefreshTokenParams struct {
	TokenHash string
	ClientID  string
	UserID    pgtype.UUID
	Scope     string
	Resource  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOAuthRefreshToken(ctx context.Context, arg CreateOAuthRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createOAuthRefreshToken,
		arg.TokenHash,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.Resource,
		arg.ExpiresAt,
	)
	return err
}

const deleteAuthCode = `-- name: DeleteAuthCode :exec
DELETE FROM oauth_auth_codes
WHERE code_hash = $1
`

func (q *Queries) DeleteAuthCode(ctx context.Context, codeHash string) error {
	_, err := q.db.Exec(ctx, deleteAuthCode, codeHash)
	return err
}

const getAuthCode = `-- name: GetAuthCode :one
SELECT code_hash, client_id, user_id, redirect_uri, code_challenge, scope, resource, expires_at, created_at FROM oauth_auth_codes
WHERE code_hash = $1
`

func (q *Queries) GetAuthCode(ctx context.Context, codeHash string) (OauthAuthCode, error) {
	row := q.db.QueryRow(ctx, getAuthCode, codeHash)
	var i OauthAuthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Scope,
		&i.Resource,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT client_id, client_name, redirect_uris, created_at FROM oauth_clients
WHERE client_id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthRefreshToken = `-- name: GetOAuthRefreshToken :one
SELECT token_hash, client_id, user_id, scope, resource, expires_at, revoked_at, created_at FROM oauth_refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetOAuthRefreshToken(ctx context.Context, tokenHash string) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getOAuthRefreshToken, tokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Resource,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthConnections = `-- name: ListOAuthConnections :many
SELECT rt.client_id, c.client_name, c.redirect_uris,
       min(rt.created_at)::timestamptz AS connected_at,
       max(rt.created_at)::timestamptz AS last_token_at
FROM oauth_refresh_tokens rt
JOIN oauth_clients c ON c.client_id = rt.client_id
WHERE rt.user_id = $1 AND rt.revoked_at IS NULL AND rt.expires_at > now()
GROUP BY rt.client_id, c.client_name, c.redirect_uris
ORDER BY max(rt.created_at) DESC
`

type ListOAuthConnectionsRow struct {
	ClientID     string
	ClientName   string
	RedirectUris []string
	ConnectedAt  pgtype.Timestamptz
	LastTokenAt  pgtype.Timestamptz
}

// One row per app (client) the user has a LIVE grant with — for the "connected apps" view.
func (q *Queries) ListOAuthConnections(ctx context.Context, userID pgtype.UUID) ([]ListOAuthConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listOAuthConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOAuthConnectionsRow
	for rows.Next() {
		var i ListOAuthConnectionsRow
		if err := rows.Scan(
			&i.ClientID,
			&i.ClientName,
			&i.RedirectUris,
			&i.ConnectedAt,
			&i.LastTokenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuthConnections = `-- name: RevokeOAuthConnections :exec
UPDATE oauth_refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND client_id = $2 AND revoked_at IS NULL
`

type RevokeOAuthConnectionsParams struct {
	UserID   pgtype.UUID
	ClientID string
}

// Disconnect an app: revoke all of the user's live refresh tokens for that client.
func (q *Queries) RevokeOAuthConnections(ctx context.Context, arg RevokeOAuthConnectionsParams) error {
	_, err := q.db.Exec(ctx, revokeOAuthConnections, arg.UserID, arg.ClientID)
	return err
}

const revokeOAuthRefreshToken = `-- name: RevokeOAuthRefreshToken :exec
UPDATE oauth_refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeOAuthRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeOAuthRefreshToken, tokenHash)
	return err
}
