// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveRefreshTokensForUser = `-- name: CountActiveRefreshTokensForUser :one
SELECT COUNT(*) FROM refresh_tokens
WHERE user_id = $1
  AND expires_at > now()
`

func (q *Queries) CountActiveRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRefreshTokensForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllRefreshTokensForUser = `-- name: DeleteAllRefreshTokensForUser :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokensForUser, userID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token, user_id, expires_at, ip_address, user_agent, created_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const storeRefreshToken = `-- name: StoreRefreshToken :exec
INSERT INTO refresh_tokens (token, user_id, expires_at, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
`

type StoreRefreshTokenParams struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	IpAddress string
	UserAgent string
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, storeRefreshToken,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
