// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, is_email_verified, totp_secret, totp_enabled, failed_logins, locked_until, created_at, updated_at, name
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, is_email_verified, totp_secret, totp_enabled, failed_logins, locked_until, created_at, updated_at, name FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, is_email_verified, totp_secret, totp_enabled, failed_logins, locked_until, created_at, updated_at, name FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const incrementFailedLogins = `-- name: IncrementFailedLogins :exec
UPDATE users
SET failed_logins = failed_logins + 1,
    updated_at    = now()
WHERE id = $1
`

func (q *Queries) IncrementFailedLogins(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedLogins, id)
	return err
}

const lockUser = `-- name: LockUser :exec
UPDATE users
SET locked_until = $2,
    updated_at   = now()
WHERE id = $1
`

type LockUserParams struct {
	ID          pgtype.UUID
	LockedUntil pgtype.Timestamptz
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const resetFailedLogins = `-- name: ResetFailedLogins :exec
UPDATE users
SET failed_logins = 0,
    locked_until  = NULL,
    updated_at    = now()
WHERE id = $1
`

func (q *Queries) ResetFailedLogins(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLogins, id)
	return err
}

const updateEmailVerified = `-- name: UpdateEmailVerified :exec
UPDATE users
SET is_email_verified = true,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateEmailVerified, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2,
    updated_at    = now()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateTOTPSecret = `-- name: UpdateTOTPSecret :exec
UPDATE users
SET totp_secret  = $2,
    totp_enabled = $3,
    updated_at   = now()
WHERE id = $1
`

type UpdateTOTPSecretParams struct {
	ID          pgtype.UUID
	TotpSecret  pgtype.Text
	TotpEnabled bool
}

func (q *Queries) UpdateTOTPSecret(ctx context.Context, arg UpdateTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, updateTOTPSecret, arg.ID, arg.TotpSecret, arg.TotpEnabled)
	return err
}
